---
- name: copy sample files to kubernetes-master
  hosts: kubernetes-master
  remote_user: root
  tasks:

  - name: create dir at master
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm
      - /root/02_k8s-csi
      - /root/03_demo

  - name: copy files to 01_kubeadm
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-master.yml

  - name: copy files to 03_demo
    copy:
      dest: /root/03_demo/
      src: "{{ item }}"
    with_items:
      - files/03_demo/mongodb-key.txt
      - files/03_demo/mongodb-service.yaml
      - files/03_demo/mongodb-statefulset.yaml
      - files/03_demo/mongodb-storageclass.yaml

  - name: copy files to 02_k8s-csi
    copy:
      dest: /root/02_k8s-csi/
      src: "{{ item }}"
    with_items:
      - files/02_k8s-csi/vsphere.conf
      - files/02_k8s-csi/csi-vsphere.conf
      - files/02_k8s-csi/csi-driver-rbac.yaml
      - files/02_k8s-csi/csi-driver-deploy.yaml

- name: copy sample files to kubernetes-worker
  hosts: kubernetes-worker
  remote_user: root
  tasks:

  - name: create dir at worker
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm

  - name: copy files to 01_kubeadm
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-worker.yml

