---
- name: setup k8s master node
  hosts: kubernetes-master
  remote_user: root
  tasks:

  - name: kubeadm init
    shell: "kubeadm init --config /root/01_kubeadm/kubeadm-init-master.yml"

  - name: create .kube dir
    file:
      path: /root/.kube
      state: directory

  - name: set .kube/config
    command:
      cmd: cp /etc/kubernetes/admin.conf /root/.kube/config

  - name: change owner .kube/config
    file:
      path: /root/.kube/config
      owner: root
      group: root

  - name: generate discovery.yml
    shell: "kubectl -n kube-public get configmap cluster-info -o jsonpath='{.data.kubeconfig}' > /etc/kubernetes/discovery.yml"

  - name: deploy flannel
    shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml"

  - name: get discovery.yml
    command:
      cmd: "scp -o StrictHostKeyChecking=no root@{{ ansible_host }}:/etc/kubernetes/discovery.yml ./files/discovery.yml"
    delegate_to: localhost


- name: setup k8s worker node
  hosts: kubernetes-worker
  remote_user: root
  tasks:

  - name: copy discovery.yml
    copy:
      src: ./files/discovery.yml
      dest: /etc/kubernetes/discovery.yml

  - name: kubeadm join
    shell: "kubeadm join --config /root/01_kubeadm/kubeadm-init-worker.yml"

