---
- name: firewall setup for k8s
  hosts: all
  remote_user: root

  tasks:
  - name: enable firewalld
    service:
      name: firewalld
      enabled: true
      state: started
    tags: always

  - name: enable firewalld masquerade
    firewalld:
      masquerade: true
      state: enabled
      permanent: true
      immediate: true
    notify:
      - restart firewalld
    tags: always

  - name: open k8s firewall
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 6443/tcp
      - 2379-2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
      - 30000-32767/tcp
    notify:
      - restart firewalld
    tags: always

  - name: open firewall for flannel and canal
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 8285/udp
      - 8472/udp
    notify:
      - restart firewalld
    tags: [ never, flannel, canal ]

  - name: open firewall for calico and canal
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 179/tcp
      - 4789/udp
      - 5473/tcp
    notify:
      - restart firewalld
    tags: [ never, calico, canal ]

  - name: open firewall for antrea vxlan
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 4789/udp
    notify:
      - restart firewalld
    tags: [ never, antrea_vxlan ]

  - name: open firewall for antrea geneve
    firewalld:
      port: "{{ item }}"
      permanent: true
      immediate: true
      state: enabled
    with_items:
      - 6081/udp
    notify:
      - restart firewalld
    tags: [ never, antrea_geneve ]

  handlers:
  - name: restart firewalld
    service:
      name: firewalld
      enabled: true
      state: restarted

