---
- name: copy sample files to kubernetes-master
  hosts: kubernetes-master
  remote_user: root
  tasks:

  - name: create dir at master
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm
      - /root/02_k8s-csi
      - /root/03_demo
    tags: always

  - name: copy files to 01_kubeadm for flannel and canal
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-master.yml
    tags: [ flannel, canal, antrea ]

  - name: copy files to 01_kubeadm for calico
    copy:
      src: files/01_kubeadm/kubeadm-init-master_calico.yml
      dest: /root/01_kubeadm/kubeadm-init-master.yml
    tags: [ calico, never ]

  - name: copy files to antrea vxlan
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/antrea_vxlan.yml
    tags: [ antrea_vxlan, never ]

  - name: copy files to antrea geneve
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/antrea_geneve.yml
    tags: [ antrea_geneve, never ]

  - name: copy files to 02_k8s-csi
    copy:
      dest: /root/02_k8s-csi/
      src: "{{ item }}"
    with_items:
      - files/02_k8s-csi/vsphere.conf
      - files/02_k8s-csi/csi-vsphere.conf
      - files/02_k8s-csi/csi-driver-rbac.yaml
      - files/02_k8s-csi/csi-driver-deploy.yaml
    tags: always

  - name: copy files to 03_demo
    copy:
      dest: /root/03_demo/
      src: "{{ item }}"
    with_items:
      - files/03_demo/yelb.yaml
    tags: always

- name: copy sample files to kubernetes-worker
  hosts: kubernetes-worker
  remote_user: root
  tasks:

  - name: create dir at worker
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm
    tags: always

  - name: copy files to 01_kubeadm
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-worker.yml
    tags: always

