---
- name: get admin kubeconfig
  hosts: kubernetes-master
  remote_user: root
  tasks:

  - name: get admin.conf
    command:
      cmd: "scp -o StrictHostKeyChecking=no root@{{ ansible_host }}:/etc/kubernetes/admin.conf ./files/admin.conf"
    delegate_to: localhost
    tags: always

- name: setup k8s fumidai
  hosts: fumidai
  remote_user: root
  tasks:

  - name: create .kube dir
    file:
      path: /root/.kube
      state: directory
    tags: always

  - name: copy .kube/config
    copy:
      src: files/admin.conf
      dest: /root/.kube/config
    tags: always

  - name: change owner .kube/config
    file:
      path: /root/.kube/config
      owner: root
      group: root
    tags: always

