---
- name: copy sample files to kubernetes-master
  hosts: kubernetes-master
  remote_user: root
  tasks:

  - name: create directories on master
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm
      - /root/02_nw-addon
      - /root/03_demo
    tags: always

  - name: copy files for master node
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-master.yml
    tags: [ flannel, canal, antrea_vxlan, antrea_geneve ]

  - name: copy files for calico master node
    copy:
      src: files/01_kubeadm/kubeadm-init-master_calico.yml
      dest: /root/01_kubeadm/kubeadm-init-master.yml
    tags: [ calico, never ]

  - name: copy files for flannel
    copy:
      dest: /root/02_nw-addon/
      src: "{{ item }}"
    with_items:
      - files/02_nw-addon/kube-flannel.yml
    tags: [ flannel ]

  - name: copy files to antrea vxlan
    copy:
      dest: /root/02_nw-addon/
      src: "{{ item }}"
    with_items:
      - files/02_nw-addon/antrea_vxlan.yml
    tags: [ antrea_vxlan, never ]

  - name: copy files to antrea geneve
    copy:
      dest: /root/02_nw-addon/
      src: "{{ item }}"
    with_items:
      - files/02_nw-addon/antrea_geneve.yml
    tags: [ antrea_geneve, never ]

  - name: copy files to 03_demo
    copy:
      dest: /root/03_demo/
      src: "{{ item }}"
    with_items:
      - files/03_demo/yelb.yml
    tags: always

- name: copy sample files to kubernetes-worker
  hosts: kubernetes-worker
  remote_user: root
  tasks:

  - name: create dir at worker
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - /root/01_kubeadm
    tags: always

  - name: copy files to 01_kubeadm
    copy:
      dest: /root/01_kubeadm/
      src: "{{ item }}"
    with_items:
      - files/01_kubeadm/kubeadm-init-worker.yml
    tags: always

